<a href="https://colab.research.google.com/github/rmishra258/Introduction/blob/master/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
"""

Linear algebra in significantly used in recommender systems - especially colllaborative filtering

Practical use of linear algebra - 
https://towardsdatascience.com/intro-to-recommender-system-collaborative-filtering-64a238194a26
"""

In [0]:
import numpy as np

In [0]:
"""
VECTOR QUANTITY

Sclar - 3 km/h, 35 Knots (does not have direction)

Vector will have magnitude and direction

5 kmph, North 
10 Knots, East 

example = [1,2,3]

"""

In [2]:
vector_1 = np.array([10,20,30,40])

vector_1

array([10, 20, 30, 40])

In [0]:
"""
Group of vectors can be called a matrix
example = [[1,2,3], [4,5,6]]
"""

In [4]:
matrix_1 = np.array([[1,2,3],
                     [4,5,6]])

matrix_1

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
"""
Vector calculations using sclar quanity

Addition
[1,2,3] + 2 = [1+2, 2+2, 3+2] = [3,4,5]

Subraction
[4,6,8] - 2 = [4-2, 6-2, 8-2] = [2,4,6]

Multiplication
[1,2,3] * 2 = [1*2, 2*2, 3*2] = [2,4,6]

Division
[2,4,6] / 2 = [2/2, 4/2, 6/2] = [1,2,3]
"""

In [7]:
#Addition
vec_1 = np.array([1,2,3])
vec_1 + 2

array([3, 4, 5])

In [8]:
#Subraction
vec_2 = np.array([4,6,8])
vec_2 - 2

array([2, 4, 6])

In [9]:
#Multiplication
vec_3 = np.array([1,2,3])
vec_3 * 2

array([2, 4, 6])

In [12]:
#Division
vec_4 = np.array([2,4,6])
vec_4 / 2

array([1., 2., 3.])

In [0]:
"""
Doing mathematical operation on a MATRIX
""" 

In [14]:
#Addition
matrix_1 = np.array([[2,4], [6,8]])
matrix_1 + 10 

array([[12, 14],
       [16, 18]])

In [15]:
#Subraction 
matrix_2 = np.array([[2,4], [6,8]])
matrix_2 - 2

array([[0, 2],
       [4, 6]])

In [16]:
#Multiplication
matrix_3 = np.array([[2,4], [6,8]])
matrix_3 * 2

array([[ 4,  8],
       [12, 16]])

In [20]:
#Division
matrix_4 = np.array([[2,4], [6,8]])
matrix_4 / 2

array([[1., 2.],
       [3., 4.]])